import type { TypecaseTheme } from "mainz/typecase";

export const draculaThemeVars = {
    "--tc-font-family":
        '"IBM Plex Sans", "Segoe UI", system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    "--tc-font-family-heading":
        '"Space Grotesk", "IBM Plex Sans", "Segoe UI", system-ui, sans-serif',
    "--tc-font-family-mono": '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
    "--tc-font-size-sm": "0.9rem",
    "--tc-font-size-md": "1rem",
    "--tc-font-size-lg": "1.1rem",
    "--tc-font-size-xl": "1.35rem",
    "--tc-title-size-sm": "1.05rem",
    "--tc-title-size-md": "1.7rem",
    "--tc-title-size-lg": "2.45rem",
    "--tc-title-size-xl": "3rem",
    "--tc-title-size-hero": "4.25rem",
    "--tc-title-weight": "600",
    "--tc-title-letter-spacing": "-0.04em",
    "--tc-title-line-height": "0.98",
    "--tc-line-height-md": "1.5",
    "--tc-space-2": "0.5rem",
    "--tc-space-3": "0.75rem",
    "--tc-space-4": "1rem",
    "--tc-space-5": "1.5rem",
    "--tc-space-6": "1.75rem",
    "--tc-space-8": "2.5rem",
    "--tc-radius-sm": "0.45rem",
    "--tc-radius-md": "0.9rem",
    "--tc-radius-lg": "1.25rem",
    "--tc-control-height-sm": "2.2rem",
    "--tc-control-height-md": "3rem",
    "--tc-control-height-lg": "3.4rem",
    "--tc-shadow-sm": "0 16px 32px rgba(12, 9, 18, 0.28)",
    "--tc-focus-ring": "0 0 0 3px rgba(189, 147, 249, 0.28)",
    "--tc-color-text": "#f8f8f2",
    "--tc-color-text-muted": "#c2bfdd",
    "--tc-color-text-subtle": "#9e9ab6",
    "--tc-color-link": "#ffb86c",
    "--tc-color-link-hover": "#ffd08f",
    "--tc-color-surface": "#1f1b2e",
    "--tc-color-surface-subtle": "#28233a",
    "--tc-color-border": "#3a3356",
    "--tc-divider-color": "#3a3356",
    "--tc-button-primary-bg": "#bd93f9",
    "--tc-button-primary-bg-hover": "#a97ff1",
    "--tc-button-primary-text": "#161320",
    "--tc-button-secondary-bg": "#2b2640",
    "--tc-button-secondary-bg-hover": "#342d4b",
    "--tc-button-secondary-border": "#4c456a",
    "--tc-button-secondary-text": "#f8f8f2",
    "--tc-button-ghost-bg-hover": "rgba(248, 248, 242, 0.08)",
    "--tc-button-ghost-text": "#f8f8f2",
    "--tc-button-danger-bg": "#ff5555",
    "--tc-button-danger-bg-hover": "#f54646",
    "--tc-button-danger-text": "#fff4f4",
    "--tc-input-bg": "#1d1930",
    "--tc-input-border": "#4c456a",
    "--tc-input-border-focus": "#bd93f9",
    "--tc-input-border-invalid": "#ff6b6b",
    "--tc-card-bg": "#221d34",
    "--tc-card-subtle-bg": "#2a2440",
    "--tc-card-border": "#3e3760",
    "--tc-root-bg": "#15121f",
    "--tc-surface-bg": "#221d34",
    "--tc-surface-bg-subtle": "#2a2440",
    "--tc-surface-border": "#3e3760",
    "--tc-surface-radius": "1.25rem",
    "--tc-surface-shadow": "0 20px 40px rgba(7, 5, 12, 0.3)",
    "--tc-list-item-text": "#d8d4ef",
    "--tc-list-item-text-active": "#ffffff",
    "--tc-list-item-bg-hover": "rgba(189, 147, 249, 0.12)",
    "--tc-list-item-bg-active": "rgba(189, 147, 249, 0.18)",
    "--tc-list-item-border-hover": "#51486f",
    "--tc-list-item-border-active": "#6b5a97",
    "--tc-meta-border": "#3e3760",
    "--tc-meta-label-color": "#b4afd0",
    "--tc-meta-value-color": "#ffffff",
    "--tc-offcanvas-bg": "#191527",
    "--tc-offcanvas-border": "#3e3760",
    "--tc-offcanvas-shadow": "0 24px 44px rgba(8, 6, 13, 0.38)",
    "--tc-offcanvas-backdrop": "rgba(9, 7, 15, 0.62)",
    "--tc-topbar-default-bg": "#191527",
    "--tc-topbar-default-border": "#3e3760",
    "--tc-topbar-default-text": "#f8f8f2",
    "--tc-topbar-default-link": "#f8f8f2",
    "--tc-topbar-default-link-hover": "#ffffff",
    "--tc-topbar-default-ghost-text": "#f8f8f2",
    "--tc-topbar-default-ghost-bg-hover": "rgba(248, 248, 242, 0.08)",
    "--tc-topbar-subtle-bg": "rgba(25, 21, 39, 0.9)",
    "--tc-topbar-subtle-border": "#3e3760",
    "--tc-topbar-subtle-text": "#f8f8f2",
    "--tc-topbar-subtle-link": "#f8f8f2",
    "--tc-topbar-subtle-link-hover": "#ffffff",
    "--tc-topbar-subtle-ghost-text": "#f8f8f2",
    "--tc-topbar-subtle-ghost-bg-hover": "rgba(248, 248, 242, 0.08)",
    "--tc-topbar-strong-bg": "#120f1b",
    "--tc-topbar-strong-border": "#4a3d70",
    "--tc-topbar-strong-text": "#f8f8f2",
    "--tc-topbar-strong-link": "#f8f8f2",
    "--tc-topbar-strong-link-hover": "#ffffff",
    "--tc-topbar-strong-ghost-text": "#f8f8f2",
    "--tc-topbar-strong-ghost-bg-hover": "rgba(248, 248, 242, 0.1)",
    "--tc-code-bg": "#171422",
    "--tc-code-header-bg": "#221d34",
    "--tc-code-border": "#3e3760",
    "--tc-code-text": "#f8f8f2",
    "--tc-code-language-color": "#b4afd0",
    "--tc-code-language-size": "0.625rem",
    "--tc-code-radius": "0.625rem",
} as const;

export const draculaTheme: TypecaseTheme = {
    name: "dracula",
    scheme: "dark",
    vars: draculaThemeVars,
};
