import type { TypecaseTheme } from "mainz/typecase";

export const editorialThemeVars = {
    "--tc-font-family":
        'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    "--tc-font-family-heading":
        '"Iowan Old Style", "Palatino Linotype", "Book Antiqua", Charter, Georgia, serif',
    "--tc-font-family-mono": '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
    "--tc-font-size-sm": "0.9rem",
    "--tc-font-size-md": "1rem",
    "--tc-font-size-lg": "1.1rem",
    "--tc-font-size-xl": "1.35rem",
    "--tc-title-size-sm": "1.05rem",
    "--tc-title-size-md": "1.7rem",
    "--tc-title-size-lg": "2.45rem",
    "--tc-title-size-xl": "3rem",
    "--tc-title-size-hero": "4.25rem",
    "--tc-title-weight": "600",
    "--tc-title-letter-spacing": "-0.045em",
    "--tc-title-line-height": "0.98",
    "--tc-line-height-md": "1.5",
    "--tc-space-2": "0.5rem",
    "--tc-space-3": "0.75rem",
    "--tc-space-4": "1rem",
    "--tc-space-5": "1.5rem",
    "--tc-space-6": "1.75rem",
    "--tc-space-8": "2.5rem",
    "--tc-radius-sm": "0.5rem",
    "--tc-radius-md": "1rem",
    "--tc-radius-lg": "1.6rem",
    "--tc-control-height-sm": "2.2rem",
    "--tc-control-height-md": "3rem",
    "--tc-control-height-lg": "3.4rem",
    "--tc-shadow-sm": "0 12px 24px rgba(31, 24, 16, 0.05)",
    "--tc-focus-ring": "0 0 0 3px rgba(17, 17, 17, 0.12)",
    "--tc-color-text": "#111111",
    "--tc-color-text-muted": "#5e564d",
    "--tc-color-text-subtle": "#7f7567",
    "--tc-color-link": "#111111",
    "--tc-color-link-hover": "#000000",
    "--tc-color-surface": "#f5efe6",
    "--tc-color-surface-subtle": "#ece2d3",
    "--tc-color-border": "#d5cabc",
    "--tc-divider-color": "#d0c4b5",
    "--tc-button-primary-bg": "#151515",
    "--tc-button-primary-bg-hover": "#000000",
    "--tc-button-primary-text": "#f9f5ef",
    "--tc-button-secondary-bg": "#f9f5ef",
    "--tc-button-secondary-bg-hover": "#efe7db",
    "--tc-button-secondary-border": "#bfb2a1",
    "--tc-button-secondary-text": "#111111",
    "--tc-button-ghost-bg-hover": "rgba(17, 17, 17, 0.06)",
    "--tc-button-ghost-text": "#111111",
    "--tc-button-danger-bg": "#7c2d12",
    "--tc-button-danger-bg-hover": "#5f220e",
    "--tc-button-danger-text": "#fff7f2",
    "--tc-input-bg": "#fbf8f3",
    "--tc-input-border": "#c9bbaa",
    "--tc-input-border-focus": "#111111",
    "--tc-input-border-invalid": "#991b1b",
    "--tc-card-bg": "#e7dccb",
    "--tc-card-subtle-bg": "#efe5d7",
    "--tc-card-border": "#ddd0bf",
    "--tc-root-bg": "#f7f2ea",
    "--tc-surface-bg": "#e7dccb",
    "--tc-surface-bg-subtle": "#efe5d7",
    "--tc-surface-border": "#ddd0bf",
    "--tc-surface-radius": "1.6rem",
    "--tc-surface-shadow": "0 12px 24px rgba(31, 24, 16, 0.04)",
    "--tc-list-item-text": "#473f36",
    "--tc-list-item-text-active": "#111111",
    "--tc-list-item-bg-hover": "rgba(17, 17, 17, 0.04)",
    "--tc-list-item-bg-active": "rgba(17, 17, 17, 0.07)",
    "--tc-list-item-border-hover": "#d5cabc",
    "--tc-list-item-border-active": "#c4b6a4",
    "--tc-meta-border": "#d0c4b5",
    "--tc-meta-label-color": "#38332d",
    "--tc-meta-value-color": "#111111",
    "--tc-offcanvas-bg": "#f9f4ec",
    "--tc-offcanvas-border": "#ddd0bf",
    "--tc-offcanvas-shadow": "0 18px 32px rgba(31, 24, 16, 0.12)",
    "--tc-offcanvas-backdrop": "rgba(17, 17, 17, 0.32)",
    "--tc-topbar-default-bg": "#f5efe6",
    "--tc-topbar-default-border": "#ddd0bf",
    "--tc-topbar-default-text": "#111111",
    "--tc-topbar-default-link": "#111111",
    "--tc-topbar-default-link-hover": "#000000",
    "--tc-topbar-default-ghost-text": "#111111",
    "--tc-topbar-default-ghost-bg-hover": "rgba(17, 17, 17, 0.06)",
    "--tc-topbar-subtle-bg": "rgba(245, 239, 230, 0.9)",
    "--tc-topbar-subtle-border": "#ddd0bf",
    "--tc-topbar-subtle-text": "#111111",
    "--tc-topbar-subtle-link": "#111111",
    "--tc-topbar-subtle-link-hover": "#000000",
    "--tc-topbar-subtle-ghost-text": "#111111",
    "--tc-topbar-subtle-ghost-bg-hover": "rgba(17, 17, 17, 0.06)",
    "--tc-topbar-strong-bg": "#171614",
    "--tc-topbar-strong-border": "#3c352d",
    "--tc-topbar-strong-text": "#f5efe6",
    "--tc-topbar-strong-link": "#f9f5ef",
    "--tc-topbar-strong-link-hover": "#ffffff",
    "--tc-topbar-strong-ghost-text": "#f9f5ef",
    "--tc-topbar-strong-ghost-bg-hover": "rgba(249, 245, 239, 0.12)",
    "--tc-code-bg": "#fbf8f3",
    "--tc-code-header-bg": "#f4ecdf",
    "--tc-code-border": "#ddd0bf",
    "--tc-code-text": "#171614",
    "--tc-code-language-color": "#5e564d",
    "--tc-code-language-size": "0.625rem",
    "--tc-code-radius": "0.625rem",
} as const;

export const editorialTheme: TypecaseTheme = {
    name: "editorial",
    scheme: "light",
    vars: editorialThemeVars,
};
