export const darkThemeVars = {
    "--tc-font-family":
        'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    "--tc-font-family-heading":
        'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    "--tc-font-family-mono": '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
    "--tc-font-size-sm": "0.875rem",
    "--tc-font-size-md": "1rem",
    "--tc-font-size-lg": "1.0625rem",
    "--tc-font-size-xl": "1.25rem",
    "--tc-title-size-sm": "1rem",
    "--tc-title-size-md": "1.5rem",
    "--tc-title-size-lg": "2rem",
    "--tc-title-size-xl": "2.5rem",
    "--tc-title-size-hero": "3.5rem",
    "--tc-title-weight": "600",
    "--tc-title-letter-spacing": "-0.03em",
    "--tc-title-line-height": "1.04",
    "--tc-line-height-md": "1.55",
    "--tc-space-2": "0.5rem",
    "--tc-space-3": "0.75rem",
    "--tc-space-4": "1rem",
    "--tc-space-5": "1.25rem",
    "--tc-space-6": "1.5rem",
    "--tc-space-8": "2rem",
    "--tc-radius-sm": "0.375rem",
    "--tc-radius-md": "0.625rem",
    "--tc-radius-lg": "0.875rem",
    "--tc-control-height-sm": "2.125rem",
    "--tc-control-height-md": "2.625rem",
    "--tc-control-height-lg": "3rem",
    "--tc-shadow-sm": "0 14px 30px rgba(0, 0, 0, 0.28)",
    "--tc-focus-ring": "0 0 0 3px rgba(96, 165, 250, 0.22)",
    "--tc-color-text": "#f8fafc",
    "--tc-color-text-muted": "#cbd5e1",
    "--tc-color-text-subtle": "#94a3b8",
    "--tc-color-link": "#93c5fd",
    "--tc-color-link-hover": "#bfdbfe",
    "--tc-color-surface": "#0f172a",
    "--tc-color-surface-subtle": "#162033",
    "--tc-color-border": "#2c3a4f",
    "--tc-divider-color": "#334155",
    "--tc-button-primary-bg": "#60a5fa",
    "--tc-button-primary-bg-hover": "#3b82f6",
    "--tc-button-primary-text": "#08111f",
    "--tc-button-secondary-bg": "#162033",
    "--tc-button-secondary-bg-hover": "#1d2940",
    "--tc-button-secondary-border": "#334155",
    "--tc-button-secondary-text": "#f8fafc",
    "--tc-button-ghost-bg-hover": "rgba(147, 197, 253, 0.14)",
    "--tc-button-ghost-text": "#f8fafc",
    "--tc-button-danger-bg": "#ef4444",
    "--tc-button-danger-bg-hover": "#dc2626",
    "--tc-button-danger-text": "#fff7f7",
    "--tc-input-bg": "#0f172a",
    "--tc-input-border": "#334155",
    "--tc-input-border-focus": "#60a5fa",
    "--tc-input-border-invalid": "#ef4444",
    "--tc-card-bg": "#111b2e",
    "--tc-card-subtle-bg": "#162033",
    "--tc-card-border": "#2c3a4f",
    "--tc-root-bg": "#0b1220",
    "--tc-surface-bg": "#111b2e",
    "--tc-surface-bg-subtle": "#162033",
    "--tc-surface-border": "#2c3a4f",
    "--tc-surface-radius": "0.875rem",
    "--tc-surface-shadow": "0 14px 30px rgba(0, 0, 0, 0.28)",
    "--tc-list-item-text": "#dbe4f0",
    "--tc-list-item-text-active": "#ffffff",
    "--tc-list-item-bg-hover": "#172235",
    "--tc-list-item-bg-active": "#1d2a40",
    "--tc-list-item-border-hover": "#334155",
    "--tc-list-item-border-active": "#475569",
    "--tc-meta-border": "#334155",
    "--tc-meta-label-color": "#cbd5e1",
    "--tc-meta-value-color": "#f8fafc",
    "--tc-offcanvas-bg": "#0f172a",
    "--tc-offcanvas-border": "#2c3a4f",
    "--tc-offcanvas-shadow": "0 20px 40px rgba(0, 0, 0, 0.36)",
    "--tc-offcanvas-backdrop": "rgba(2, 6, 23, 0.66)",
    "--tc-topbar-default-bg": "#0f172a",
    "--tc-topbar-default-border": "#2c3a4f",
    "--tc-topbar-default-text": "#f8fafc",
    "--tc-topbar-default-link": "#f8fafc",
    "--tc-topbar-default-link-hover": "#ffffff",
    "--tc-topbar-default-ghost-text": "#f8fafc",
    "--tc-topbar-default-ghost-bg-hover": "rgba(147, 197, 253, 0.14)",
    "--tc-topbar-subtle-bg": "rgba(15, 23, 42, 0.88)",
    "--tc-topbar-subtle-border": "#2c3a4f",
    "--tc-topbar-subtle-text": "#f8fafc",
    "--tc-topbar-subtle-link": "#f8fafc",
    "--tc-topbar-subtle-link-hover": "#ffffff",
    "--tc-topbar-subtle-ghost-text": "#f8fafc",
    "--tc-topbar-subtle-ghost-bg-hover": "rgba(147, 197, 253, 0.14)",
    "--tc-topbar-strong-bg": "#020617",
    "--tc-topbar-strong-border": "#1e293b",
    "--tc-topbar-strong-text": "#f8fafc",
    "--tc-topbar-strong-link": "#f8fafc",
    "--tc-topbar-strong-link-hover": "#ffffff",
    "--tc-topbar-strong-ghost-text": "#f8fafc",
    "--tc-topbar-strong-ghost-bg-hover": "rgba(255, 255, 255, 0.12)",
    "--tc-code-bg": "#0b1220",
    "--tc-code-header-bg": "#111b2e",
    "--tc-code-border": "#2c3a4f",
    "--tc-code-text": "#e2e8f0",
    "--tc-code-language-color": "#94a3b8",
    "--tc-code-language-size": "0.625rem",
    "--tc-code-radius": "0.5rem",
} as const;
