export const lightThemeVars = {
    "--tc-font-family":
        'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    "--tc-font-family-heading":
        'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    "--tc-font-family-mono": '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
    "--tc-font-size-sm": "0.875rem",
    "--tc-font-size-md": "1rem",
    "--tc-font-size-lg": "1.0625rem",
    "--tc-font-size-xl": "1.25rem",
    "--tc-title-size-sm": "1rem",
    "--tc-title-size-md": "1.5rem",
    "--tc-title-size-lg": "2rem",
    "--tc-title-size-xl": "2.5rem",
    "--tc-title-size-hero": "3.5rem",
    "--tc-title-weight": "600",
    "--tc-title-letter-spacing": "-0.03em",
    "--tc-title-line-height": "1.04",
    "--tc-line-height-md": "1.55",
    "--tc-space-2": "0.5rem",
    "--tc-space-3": "0.75rem",
    "--tc-space-4": "1rem",
    "--tc-space-5": "1.25rem",
    "--tc-space-6": "1.5rem",
    "--tc-space-8": "2rem",
    "--tc-radius-sm": "0.375rem",
    "--tc-radius-md": "0.625rem",
    "--tc-radius-lg": "0.875rem",
    "--tc-control-height-sm": "2.125rem",
    "--tc-control-height-md": "2.625rem",
    "--tc-control-height-lg": "3rem",
    "--tc-shadow-sm": "0 8px 20px rgba(15, 23, 42, 0.06)",
    "--tc-focus-ring": "0 0 0 3px rgba(37, 99, 235, 0.18)",
    "--tc-color-text": "#1f2937",
    "--tc-color-text-muted": "#4b5563",
    "--tc-color-text-subtle": "#6b7280",
    "--tc-color-link": "#2563eb",
    "--tc-color-link-hover": "#1d4ed8",
    "--tc-color-surface": "#ffffff",
    "--tc-color-surface-subtle": "#f8fafc",
    "--tc-color-border": "#d4dbe5",
    "--tc-divider-color": "#dbe3ec",
    "--tc-button-primary-bg": "#2563eb",
    "--tc-button-primary-bg-hover": "#1d4ed8",
    "--tc-button-primary-text": "#ffffff",
    "--tc-button-secondary-bg": "#ffffff",
    "--tc-button-secondary-bg-hover": "#f8fafc",
    "--tc-button-secondary-border": "#cbd5e1",
    "--tc-button-secondary-text": "#1f2937",
    "--tc-button-ghost-bg-hover": "#e5eefc",
    "--tc-button-ghost-text": "#1f2937",
    "--tc-button-danger-bg": "#dc2626",
    "--tc-button-danger-bg-hover": "#b91c1c",
    "--tc-button-danger-text": "#ffffff",
    "--tc-input-bg": "#ffffff",
    "--tc-input-border": "#cbd5e1",
    "--tc-input-border-focus": "#2563eb",
    "--tc-input-border-invalid": "#dc2626",
    "--tc-card-bg": "#ffffff",
    "--tc-card-subtle-bg": "#f8fafc",
    "--tc-card-border": "#dbe3ec",
    "--tc-root-bg": "#ffffff",
    "--tc-surface-bg": "#ffffff",
    "--tc-surface-bg-subtle": "#f8fafc",
    "--tc-surface-border": "#dbe3ec",
    "--tc-surface-radius": "0.875rem",
    "--tc-surface-shadow": "0 8px 20px rgba(15, 23, 42, 0.06)",
    "--tc-list-item-text": "#334155",
    "--tc-list-item-text-active": "#0f172a",
    "--tc-list-item-bg-hover": "#eef4ff",
    "--tc-list-item-bg-active": "#e5eefc",
    "--tc-list-item-border-hover": "#dbeafe",
    "--tc-list-item-border-active": "#bfdbfe",
    "--tc-meta-border": "#dbe3ec",
    "--tc-meta-label-color": "#4b5563",
    "--tc-meta-value-color": "#1f2937",
    "--tc-offcanvas-bg": "#ffffff",
    "--tc-offcanvas-border": "#dbe3ec",
    "--tc-offcanvas-shadow": "0 18px 32px rgba(15, 23, 42, 0.14)",
    "--tc-offcanvas-backdrop": "rgba(15, 23, 42, 0.36)",
    "--tc-topbar-default-bg": "#ffffff",
    "--tc-topbar-default-border": "#dbe3ec",
    "--tc-topbar-default-text": "#1f2937",
    "--tc-topbar-default-link": "#1f2937",
    "--tc-topbar-default-link-hover": "#111827",
    "--tc-topbar-default-ghost-text": "#1f2937",
    "--tc-topbar-default-ghost-bg-hover": "#e5eefc",
    "--tc-topbar-subtle-bg": "rgba(248, 250, 252, 0.92)",
    "--tc-topbar-subtle-border": "#dbe3ec",
    "--tc-topbar-subtle-text": "#1f2937",
    "--tc-topbar-subtle-link": "#1f2937",
    "--tc-topbar-subtle-link-hover": "#111827",
    "--tc-topbar-subtle-ghost-text": "#1f2937",
    "--tc-topbar-subtle-ghost-bg-hover": "#e5eefc",
    "--tc-topbar-strong-bg": "#6f42c1",
    "--tc-topbar-strong-border": "#5f36ab",
    "--tc-topbar-strong-text": "#f8f5ff",
    "--tc-topbar-strong-link": "#ffffff",
    "--tc-topbar-strong-link-hover": "#efe7ff",
    "--tc-topbar-strong-ghost-text": "#ffffff",
    "--tc-topbar-strong-ghost-bg-hover": "rgba(255, 255, 255, 0.18)",
    "--tc-code-bg": "#ffffff",
    "--tc-code-header-bg": "#f8fafc",
    "--tc-code-border": "#dbe3ec",
    "--tc-code-text": "#0f172a",
    "--tc-code-language-color": "#334155",
    "--tc-code-language-size": "0.625rem",
    "--tc-code-radius": "0.5rem",
} as const;
